//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfUP_GM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        public int Id { get; set; }
        public int TypeBid { get; set; }
        public string Text { get; set; }
        public int UserID { get; set; }
    
        public virtual TypeBid TypeBid1 { get; set; }
        public virtual User User { get; set; }
    }
}
