//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfUP_GM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UP_GMEntities : DbContext
    {
        public UP_GMEntities()
            : base("name=UP_GMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bid> Bid { get; set; }
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<BookInList> BookInList { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<GenreBook> GenreBook { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<Rewiew> Rewiew { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeBid> TypeBid { get; set; }
        public virtual DbSet<TypeBookList> TypeBookList { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
