//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfUP_GM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportAuthor
    {
        public int id { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Report Report { get; set; }
        public virtual User User { get; set; }
    }
}
