//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfUP_GM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int id { get; set; }
        public int UserID { get; set; }
        public string Text { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Book Book { get; set; }
        public virtual Rewiew Rewiew { get; set; }
        public string Type => GetTypeReport();

        public string GetTypeReport()
        {
            if (User1 != null)
            {
                return $"жалоба на автора {User1.login}";
            }
            else if (Book != null)
            {
                return $"жалоба на книгу {Book.Name} автора {Book.User.login}";
            }
            else
            {
                return $"жалоба на отзыв пользователя {Rewiew.User.login}";
            }
        }
    }
}
