//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfUP_GM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rewiew
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rewiew()
        {
            this.Report = new HashSet<Report>();
        }
    
        public int id { get; set; }
        public int UserID { get; set; }
        public double Rating { get; set; }
        public string Text { get; set; }
        public Nullable<int> BookID { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Report { get; set; }
    }
}
